spring:
  application:
    name: ecommercemg
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercemg?createDatabaseIfNotExist=true
    username: root
    password: magaby2280@
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900          # 15 minutes
    refreshTokenExpiration: 604800      # 7 days
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost4242        #frontend app port